apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:miruohotspring/k8s-home.git
    targetRevision: v0.2.0
    path: infra/secrets
    directory:
      recurse: true
      include: "*-sealed.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
