apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://concourse-charts.storage.googleapis.com/
      chart: concourse
      targetRevision: 18.5.0
      helm:
        valueFiles:
          - $values/apps/concourse/values.yaml
        parameters:
          - name: postgresql.image.repository
            value: bitnami/postgresql
          - name: postgresql.image.tag
            value: latest
          - name: postgresql.image.digest
            value: sha256:c47e54a69b39aa97d4405d68ea02bf2ffe06b646748e2ddf9c761416ead6acd5
    - repoURL: https://github.com/miruohotspring/k8s-home.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/miruohotspring/k8s-home.git
      targetRevision: main
      path: apps/concourse/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: concourse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
