apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://concourse-charts.storage.googleapis.com/
      chart: concourse
      targetRevision: 18.5.0
      helm:
        valueFiles:
          - $values/infra/concourse/values.yaml
    - repoURL: git@github.com:miruohotspring/k8s-home.git
      targetRevision: v0.1.0
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: concourse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
