apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://concourse-charts.storage.googleapis.com/
      chart: concourse
      targetRevision: 18.5.0
      helm:
        valueFiles:
          - $values/infra/concourse/values.yaml
    - repoURL: git@github.com:miruohotspring/k8s-home.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: concourse
  ignoreDifferences:
    # Concourse chart renders duplicate env keys (CONCOURSE_ADD_LOCAL_USER) when also
    # injecting web.env. Argo CD can throw ComparisonError due to setElementOrder
    # mismatch, which blocks reconciliation. Ignore env diffs to keep sync healthy.
    - group: apps
      kind: Deployment
      name: concourse-web
      namespace: concourse
      jsonPointers:
        - /spec/template/spec/containers/0/env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
