apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
type: Opaque
# NOTE: Replace this sample via `kubectl create secret` in real environments.
data:
  TUNNEL_TOKEN: "<BASE64_ENCODED_TUNNEL_TOKEN>"
